build.sh
@Praburaj 
This is blocking build on CI. Updating the path to point to the right kvm.sh file
=> Updating path to kvm

test/E2ETests/NtlmAuthentationTest.cs
The other two tests already have this.
=> Adding a retry logic for NtlmAuth test

test/E2ETests/NtlmAuthentationTest.cs
Deleted a boolean flag passed to ignore login/register links in the home page.
=> Fixing a test regression

test/E2ETests/Common/DeploymentUtility.cs
=> Increase wait time for server to start

src/MusicStore.Spa/Infrastructure/BuddyValidatorProvider.cs
=> Fixing build break due to model binding changes

test/E2ETests/compiler/shared/Mocks/StartupSocialTesting.cs
=> Adding authorization policy for the missed startup class.

test/E2ETests/Implementation/Scenarios.cs
=> Changing an error string in the tests due to identity change.

test/E2ETests/Common/Helpers.cs
=> Increasing the retry count

src/MusicStore/wwwroot/web.config
React to https://github.com/aspnet/Helios/pull/83
=> Change K_DETAILED_ERRORS to ASPNET_DETAILED_ERRORS

src/MusicStore/CopyAspNetLoader.cmd
Changing default packages path to `%USERPROFILE%/.kpm/packages` to `%USERPROFILE%/.dotnet/packages`
@davidfowl @Praburaj
=> React to default packages path change in runtime

src/MusicStore.Spa/project.json, src/MusicStore/project.json, test/E2ETests/Common/DeploymentUtility.cs, test/E2ETests/Common/StartParameters.cs, test/E2ETests/PublishAndRunTests.cs
React to aspnet/KRuntime#967
@Praburaj @davidfowl
=> React to kpm subcommand renaming

test/E2ETests/Implementation/OpenIdConnectLoginScenarios.cs, test/E2ETests/compiler/shared/Mocks/OpenIdConnect/CustomStringDataFormat.cs, test/E2ETests/compiler/shared/Mocks/OpenIdConnect/OpenIdConnectBackChannelHttpHandler.cs, test/E2ETests/compiler/shared/Mocks/OpenIdConnect/OpenIdConnectNotifications.cs, test/E2ETests/compiler/shared/Mocks/StartupOpenIdConnectTesting.cs
Adding the full E2E test for OpenIdConnect
=> E2Etest for OpenIdConnect

src/MusicStore/CopyAspNetLoader.cmd, src/MusicStore/wwwroot/web.config, test/E2ETests/Common/DeploymentUtility.cs, test/E2ETests/Common/DotnetArchitecture.cs, test/E2ETests/Common/DotnetFlavor.cs, test/E2ETests/Common/IISApplication.cs, test/E2ETests/Common/StartParameters.cs, test/E2ETests/NtlmAuthentationTest.cs, test/E2ETests/PublishAndRunTests.cs, test/E2ETests/SmokeTests.cs
=> React to runtime renaming revert

src/MusicStore/Views/Shared/_Layout.cshtml, test/E2ETests/Implementation/Scenarios.cs
=> Changing codeplex -> github.com/aspnet/musicstore

src/MusicStore/Startup.cs, src/MusicStore/StartupNtlmAuthentication.cs, test/E2ETests/Implementation/Scenarios.cs, test/E2ETests/compiler/shared/Mocks/StartupSocialTesting.cs
=> Printing the runtime information at the beginning of the test

src/MusicStore/Controllers/AccountController.cs, test/E2ETests/Common/DeploymentUtility.cs, test/E2ETests/Common/Helpers.cs, test/E2ETests/Implementation/OpenIdConnectLoginScenarios.cs, test/E2ETests/Implementation/Scenarios.cs, test/E2ETests/NtlmAuthentationTest.cs, test/E2ETests/OpenIdConnectTests.cs, test/E2ETests/PublishAndRunTests.cs, test/E2ETests/SmokeTests.cs, test/E2ETests/compiler/shared/Mocks/OpenIdConnect/OpenIdConnectNotifications.cs
As well removed the logic to wait for the creation of the db file in userprofile folder
as we now have retry logic.
=> Adding verification for openIdconnect logout flow

test/E2ETests/Implementation/OpenIdConnectLoginScenarios.cs
Using a non-redirecting handler while sending logout request to shield from external changes.
=> Fixing test

src/MusicStore/Areas/Admin/Controllers/StoreManagerController.cs, src/MusicStore/Areas/Admin/Views/StoreManager/Details.cshtml, src/MusicStore/Areas/Admin/Views/StoreManager/Edit.cshtml, src/MusicStore/Controllers/CheckoutController.cs, src/MusicStore/Controllers/HomeController.cs, src/MusicStore/Controllers/ShoppingCartController.cs, src/MusicStore/Controllers/StoreController.cs, src/MusicStore/Startup.cs, src/MusicStore/StartupNtlmAuthentication.cs, src/MusicStore/StartupOpenIdConnect.cs, src/MusicStore/Views/Shared/StatusCodePage.cshtml, test/E2ETests/Implementation/Scenarios.cs, test/E2ETests/SmokeTests.cs, test/E2ETests/compiler/shared/Mocks/StartupOpenIdConnectTesting.cs, test/E2ETests/compiler/shared/Mocks/StartupSocialTesting.cs
Adding some automation as well.
=> Using statuscode pages in the sample

test/E2ETests/project.json
Uncommented section seems to throw on build.cmd
=> Removing aspnetcore50 from test project.json

src/MusicStore.Spa/Helpers/AngularExtensions.cs, src/MusicStore.Spa/Infrastructure/BuddyModelMetadataProvider.cs
Updated to account for: https://github.com/aspnet/Mvc/commit/9d5364cf9b5e1bd4961946ec26379500a4f7720f
=> React to MVC changes.

src/MusicStore/Views/Shared/_LoginPartial.cshtml, test/E2ETests/NtlmAuthentationTest.cs
User.IsSignedIn() does not return true for NTLM. So pulling the NTLM check out of the code block.
=> Re-enable the Ntlm authentication tests

test/E2ETests/Implementation/Scenarios.cs
=> React to aspnet/Mvc#2076 changes

.deployment, README.md, app.json
I've signed the CLA. Will also send PR to dev branch. Supersedes https://github.com/aspnet/MusicStore/pull/327
=> Add heroku button

src/MusicStore/Models/Order.cs, src/MusicStore/Views/Checkout/AddressAndPayment.cshtml
=> Remove [Required] from the Order model to fix a test failure

build.cmd, build.sh, src/MusicStore.Spa/project.json, src/MusicStore/CopyAspNetLoader.cmd, src/MusicStore/Helios.cmd, src/MusicStore/project.json, test/E2ETests/Common/DeploymentUtility.cs, test/E2ETests/Common/Helpers.cs, test/E2ETests/Common/IISApplication.cs, test/E2ETests/Common/StartParameters.cs, test/E2ETests/Implementation/Scenarios.cs, test/E2ETests/OpenIdConnectTests.cs, test/E2ETests/SmokeTests.cs, test/E2ETests/compiler/shared/Mocks/StartupSocialTesting.cs, test/E2ETests/project.json, test/E2ETests/xunit/SkipIfCurrentRuntimeIsCoreClr.cs, test/MusicStore.Spa.Test/project.json, test/MusicStore.Test/project.json
Prepping to be merged once ready.
=> Update aspnet50/aspnetcore50 => dnx50/dnxcore50.

src/MusicStore/Models/MusicStoreContext.cs
=> Reacting to changes in Ef disable use of identity column

src/MusicStore/Areas/Admin/Views/StoreManager/Index.cshtml
=> React to razor changes

README.md, test/E2ETests/Common/DeploymentUtility.cs
https://github.com/aspnet/Universe/issues/186
@davidfowl @muratg
=> Rename kpm to dnu

src/MusicStore.Spa/Models/SampleData.cs, src/MusicStore.Spa/Startup.cs, src/MusicStore/Startup.cs, src/MusicStore/StartupOpenIdConnect.cs, test/E2ETests/compiler/shared/Mocks/StartupOpenIdConnectTesting.cs, test/E2ETests/compiler/shared/Mocks/StartupSocialTesting.cs, test/MusicStore.Test/ManageControllerTest.cs
@Praburaj 
Update namespace for Identity models
=> React to Identity changes

src/MvcMusicStore.Spa/Models/SampleData.cs, src/MvcMusicStore/Models/SampleData.cs
@Praburaj 
We have this one unmerged commit from release to dev. Need to verify if this is good to merge
=> Fixing a build break in .net 4.5 version of projects

README.md, build.sh, src/MusicStore/Program.cs, src/MusicStore/Startup.cs
https://github.com/aspnet/dnx/issues/1473
@davidfowl @Praburaj @muratg
=> Remove k command and use dnx instead

src/MusicStore/Views/Manage/ManageLogins.cshtml
=> Fixing the namespace in the sample view page

src/MusicStore.Spa/Models/Order.cs, src/MusicStore/Models/Order.cs, src/MvcMusicStore.Spa/Models/Order.cs, src/MvcMusicStore/Models/Order.cs
=> fixed typo

src/MusicStore.Spa/project.json, src/MusicStore/project.json, test/E2ETests/Common/DeploymentUtility.cs, test/E2ETests/Common/StartParameters.cs, test/E2ETests/PublishAndRunTests.cs
https://github.com/aspnet/dnx/issues/1474
@muratg @davidfowl @Praburaj
=> Rename "dnu bundle" to "dnu publish"

test/E2ETests/Common/DeploymentUtility.cs
Fixing MusicStore/dev build on CI
@Praburaj
=> Fix newly added --no-source variations

src/MusicStore.Spa/Startup.cs, src/MusicStore/Models/SampleData.cs, src/MusicStore/Startup.cs, src/MusicStore/StartupNtlmAuthentication.cs, src/MusicStore/StartupOpenIdConnect.cs, test/E2ETests/compiler/shared/Mocks/StartupOpenIdConnectTesting.cs, test/E2ETests/compiler/shared/Mocks/StartupSocialTesting.cs
=> React to configuration model change

src/MusicStore/wwwroot/web.config, test/DeploymentHelpers/Deployers/IISExpressDeployer.cs
=> Setting DNX_APPBASE from the deployment helpers

src/MusicStore/Startup.cs, src/MusicStore/StartupOpenIdConnect.cs, test/E2ETests/compiler/shared/Mocks/StartupOpenIdConnectTesting.cs, test/E2ETests/compiler/shared/Mocks/StartupSocialTesting.cs
=> Using IRuntimeEnvironment to detect if mono

src/MusicStore/Models/SampleData.cs
=> Creating 100 sample users in sample data when it is run in Performance Lab

test/E2ETests/NtlmAuthentationTest.cs, test/E2ETests/SmokeTests.cs
@victorhurdugaci 
https://github.com/aspnet/Testing/pull/102
=> React to OperationSystems option change

src/MusicStore/Platform.cs, src/MusicStore/Startup.cs, src/MusicStore/StartupOpenIdConnect.cs
The SQL client doesn't work well on the Nano server so for now we'll use the in memory store.
Please review @suhasj
=> Use the in memory store on the Nano server

src/MusicStore.Spa/Models/SampleData.cs, src/MusicStore/Models/SampleData.cs
@mikary @bricelam 
DbContext.Database is now of type RelationalDatabase instead of SqlServerDatabase. This is working fine so do let me know if this is not the case
=> Fixing database changes from EF

test/MusicStore.Test/project.json, test/RemoteTest.cmd, test/RemoteTest.ps1, tools/BundleAndDeploy.cmd, tools/BundleAndDeploy.ps1
- Music Store tests running on CoreCLR
- Script to run the unit tests on a remote machine
=> Remote test run

test/E2ETests/PublishAndRunTests.cs, test/E2ETests/SmokeTests.cs
=> Disabling tests to unblock CI

src/MusicStore.Spa/Controllers/AccountController.cs, src/MusicStore/Controllers/AccountController.cs
=> React to identity rename

src/MusicStore/Controllers/AccountController.cs
=> Clear session data on log off

src/MusicStore/Platform.cs, src/MusicStore/Startup.cs
For release branch
@danroth27 @kichalla
=> Make work on Xplat CoreCLR

src/MusicStore/Areas/Admin/Controllers/StoreManagerController.cs, src/MusicStore/Startup.cs, src/MusicStore/StartupNtlmAuthentication.cs, src/MusicStore/StartupOpenIdConnect.cs, src/MusicStore/Views/Account/_ExternalLoginsListPartial.cshtml, src/MusicStore/Views/Manage/ManageLogins.cshtml
Just cleaning up the sample even further by using some APIs that were introduced a while back.
@kichalla @dougbu
=> Remove unneeded namespaces, use new startup APIs

src/MusicStore/project.json
:watch: https://github.com/aspnet/EntityFramework/pull/3331
=> React to EF rename

NuGet.config
=> azureadwebstack release feed

src/MusicStore/Views/_ViewImports.cshtml
- react to aspnet/Razor#561 fix: PR aspnet/Razor#591 and commit aspnet/Razor@0c95315
=> Remove quotes from `@addTagHelper` directive

src/MusicStore/config.json, test/E2ETests/Common/DbUtils.cs
=> Increase connect timeout in music store tests

MusicStore.sln, NuGet.config, shared/Mocks/Facebook/FacebookMockBackChannelHttpHandler.cs, src/MusicStore/wwwroot/web.config, test/E2ETests/Implementation/FacebookLoginScenarios.cs
=> Fix facebook tests.

src/MusicStore/CopyAspNetLoader.cmd, src/MusicStore/Helios.cmd, test/E2ETests/project.json
https://github.com/aspnet/Coherence-Signed/issues/117
=> Cleanup `Microsoft.AspNet.Server.IIS` usage.

src/MusicStore/Controllers/ShoppingCartController.cs, src/MusicStore/Startup.cs, src/MusicStore/Views/ShoppingCart/Index.cshtml, test/MusicStore.Test/ShoppingCartControllerTest.cs
=>  * Use suggested Antiforgery AJAX patern.

src/MusicStore/project.json
=> Remove Mvc CodeGenerator

src/MusicStore/Components/GenreMenuComponent.cs, src/MusicStore/Controllers/HomeController.cs, src/MusicStore/Models/CartItem.cs, src/MusicStore/Models/MusicStoreContext.cs, src/MusicStore/Models/SampleData.cs, src/MusicStore/Models/ShoppingCart.cs, test/MusicStore.Test/Models/ShoppingCartTest.cs
=> Cleanup some EF TODOs

test/MusicStore.Test/TestSession.cs
- see issue aspnet/HttpAbstractions#590 and pull aspnet/HttpAbstractions#589
=> React to HttpAbstractions change: `WebSocketAcceptContext` in new namespace

src/MusicStore/Program.cs, src/MusicStore/project.json, src/MusicStore/wwwroot/web.config, test/E2ETests/Http.config, test/E2ETests/Implementation/Validator.cs, test/E2ETests/NtlmAuthentationTest.cs, test/E2ETests/OpenIdConnectTests.cs, test/E2ETests/PublishAndRunTests.cs, test/E2ETests/SmokeTests.cs
I am able to run these tests locally with the old packages. Will need to test with newer packages once we have a Coherence build.
cc @Tratcher @shirhatti
=> Enable IISExpress tests

shared/Mocks/OpenIdConnect/OpenIdConnectBackChannelHttpHandler.cs, src/MusicStore/Controllers/AccountController.cs, test/E2ETests/Implementation/OpenIdConnectLoginScenarios.cs, test/E2ETests/OpenIdConnectTests.cs
=> Enable OpenId Tests

src/MusicStore/Controllers/AccountController.cs, src/MusicStore/Controllers/CheckoutController.cs, src/MusicStore/Controllers/ShoppingCartController.cs, src/MusicStore/Startup.cs, src/MusicStore/project.json, test/E2ETests/project.json, test/MusicStore.Test/CheckoutControllerTest.cs, test/MusicStore.Test/ShoppingCartControllerTest.cs
=> Add logging to 'business' events

src/MusicStore/Components/CartSummaryComponent.cs, src/MusicStore/Components/GenreMenuComponent.cs, src/MusicStore/Controllers/HomeController.cs, src/MusicStore/Models/MusicStoreContext.cs, src/MusicStore/Models/ShoppingCart.cs, src/MusicStore/Startup.cs
1) Queries are untracked by default.
2) Use projection query in CartSummaryComponent.
3) Removed redundant async methods.
=> Minor improvements to EF usage.

src/MusicStore/Components/GenreMenuComponent.cs, src/MusicStore/Controllers/ShoppingCartController.cs, src/MusicStore/Models/CartItem.cs, src/MusicStore/Models/ShoppingCart.cs, src/MusicStore/Startup.cs, src/MusicStore/Views/Shared/Components/GenreMenu/Default.cshtml
- Use more efficient projection query for GenreMenuComponent.
- Change some sync EF calls to async.
- Log at Information level when Development.
=> Various EF usage improvements

src/MusicStore/Areas/Admin/Controllers/StoreManagerController.cs, src/MusicStore/Controllers/HomeController.cs, src/MusicStore/Controllers/StoreController.cs, src/MusicStore/Properties/AppSettings.cs, src/MusicStore/config.json, test/MusicStore.Test/HomeControllerTest.cs, test/MusicStore.Test/StoreControllerTest.cs, test/MusicStore.Test/TestAppSettings.cs
@SajayAntony @martinpf @Tratcher
=> Created a configurable memory cache

shared/Mocks/StartupSocialTesting.cs, test/E2ETests/RemoteDeploymentConfig.cs, test/E2ETests/SmokeTestHelper.cs, test/E2ETests/SmokeTests.cs, test/E2ETests/SmokeTestsOnNanoServer.cs, test/E2ETests/project.json, test/E2ETests/remoteDeploymentConfig.json
@Tratcher @victorhurdugaci @muratg
=> Added smoke tests to verify on Nano server

test/E2ETests/Implementation/Validator.cs, test/E2ETests/NtlmAuthentationTest.cs, test/E2ETests/OpenIdConnectTests.cs, test/E2ETests/PublishAndRunTests.cs, test/E2ETests/SmokeTestHelper.cs
[Fixes #642] Show test progress when running functional tests
@Eilon @natemcmaster
=> Added console write statements to improve user experience

src/MusicStore/Platform.cs
https://github.com/aspnet/MusicStore/issues/658. 
Review: @victorhurdugaci 
Approval: @Eilon @DamianEdwards
=> Recognize new variants of nano server product types

src/MusicStore/Controllers/ShoppingCartController.cs, src/MusicStore/Models/ShoppingCart.cs
@sivagms @martinpf 
This dramatically reduces the content we're throwing into the log.
=> Fixes null reference exception

test/E2ETests/SmokeTests.cs
Temporarily to get a build.
#673
@troydai
=> Disable failing tests (#673).

src/MusicStore/Platform.cs, src/MusicStore/Startup.cs
=> Remove PlatformAbstractions

test/E2ETests/OpenIdConnectTests.cs, test/E2ETests/SmokeTests.cs
#627 Tested locally on mac.
cc @BrennanConroy 
approval: @Eilon
=> Re-enable tests disabled due to corefx issue

test/E2ETests/Implementation/OpenIdConnectLoginScenarios.cs
https://github.com/aspnet/Security/pull/925
/cc @AndriySvyryd @Tratcher
=> Fix OpenIdConnect test

samples/MusicStore.Standalone/project.json, samples/MusicStore/project.json
cref https://github.com/aspnet/IISIntegration/pull/259
cc @Tratcher
=> Downgrade dotnet-publish-iis to latest stable release

samples/MusicStore.Standalone/project.json, samples/MusicStore/project.json
=> Use AspNetCore meta package

src/MusicStore.Standalone/project.json, src/MusicStore/project.json
=> Update WebListener version to 1.0.

samples/MusicStore.Standalone/project.json, samples/MusicStore/project.json
@natemcmaster @pranavkm @moozzyk
=> Update Microsoft.AspNetCore.Server.IISIntegration.Tools to 1.1.0-preview4-final

samples/MusicStore/ForTesting/Mocks/Facebook/TestFacebookEvents.cs, samples/MusicStore/ForTesting/Mocks/Google/TestGoogleEvents.cs, samples/MusicStore/ForTesting/Mocks/MicrosoftAccount/TestMicrosoftAccountEvents.cs
Just FYI, merging to unblock build
=> React to Security changes

MusicStore.sln, build/dependencies.props, test/E2ETests/E2ETests.csproj, test/E2ETests/Http.config, test/E2ETests/NtlmAuthentation.config, test/E2ETests/NtlmAuthentationTest.cs, test/E2ETests/OpenIdConnectTests.cs, test/E2ETests/PublishAndRunTests.cs, test/E2ETests/SmokeTests.cs, test/E2ETests/SmokeTestsOnNanoServer.cs
The saga never ends. Or does it? I think this is the last one!
Thanks to @moozzyk 's VS extension, my eyes burn whenever I see trailing whitespace or lines with only whitespace, hence the tidy up in some IIS configs.
Related to aspnet/Hosting#996
=> react to aspnet/Hosting#996

test/MusicStore.E2ETests/Implementation/OpenIdConnectLoginScenarios.cs
https://github.com/aspnet/HttpAbstractions/pull/844
=> React to StringSegment change

test/MusicStore.E2ETests/NtlmAuthentationTest.cs, test/MusicStore.E2ETests/SmokeTests_X64.cs
=> Disabling tests while investigating file location issues

build/dependencies.props, test/MusicStore.E2ETests/NtlmAuthentationTest.cs, test/MusicStore.E2ETests/SmokeTests_X64.cs
This reverts commit 6294d38805c555a3c92dbdf79738a4cdcec5a55e.
Addresses https://github.com/aspnet/MusicStore/issues/830
=> Revert "Disabling tests while investigating file location issues (#831)"

test/MusicStore.E2ETests/NtlmAuthentationTest.cs, test/MusicStore.E2ETests/SmokeTests_X64.cs
```
[10:47:05][Step 5/6]    | Microsoft.AspNetCore.Server.IntegrationTesting.IISExpressDeployer Information: Deploying [Variation] :: ServerType=IISExpress, Runtime=CoreClr, Arch=x64, BaseUrlHint=, Publish=False
[10:47:05][Step 5/6]    | Microsoft.AspNetCore.Server.IntegrationTesting.IISExpressDeployer Information: SET ASPNETCORE_ENVIRONMENT=HelloWorld
[10:47:05][Step 5/6]    | Microsoft.AspNetCore.Server.IntegrationTesting.IISExpressDeployer Information: Executing command dotnet publish  --output "C:\b\t\buildTmp\30f7e4b4-801e-40eb-b699-944e56266508" --framework netcoreapp2.0 --configuration Release --no-restore 
[10:47:05][Step 5/6]    | Microsoft.AspNetCore.Server.IntegrationTesting.IISExpressDeployer Information: dotnet-publish stdout: Microsoft (R) Build Engine version 15.6.12.27473 …
```
=> Disabling tests while investigating ANCM responding with 400 status code.

samples/MusicStore/MusicStore.csproj
As ANCM is now an internal dependency, we can't build it on Mac or Linux.
=> Make the ANCM a conditional dependency 

.travis.yml, build/dependencies.props, test/MusicStore.E2ETests/Implementation/Validator.cs
Caused by dotnet/corefx#27912 ?
=> [Testing] Debugging some tests that only fail on High Sierra

build/dependencies.props, build/repo.props, samples/MusicStore/Program.cs, samples/MusicStore/Startup.cs, samples/MusicStore/StartupNtlmAuthentication.cs, test/MusicStore.E2ETests/DotnetRunTests.cs, test/MusicStore.E2ETests/Implementation/Validator.cs, test/MusicStore.E2ETests/NtlmAuthentationTest.cs, test/MusicStore.E2ETests/PublishAndRunTests.cs
Depends on https://github.com/aspnet/Hosting/pull/1429
=> Re-enable x86 test variants
