aspnet/MusicStore

test/E2ETests/Common/DeploymentUtility.cs
Right now since console logger is enabled there seems more delay in app start.
@suhasj
=> Increasing wait time out on mono tests

test/E2ETests/OpenIdConnectTests.cs, test/E2ETests/compiler/shared/Mocks/OpenIdConnect/OpenIdConnectNotifications.cs
Seems like the External cookie is null though openidc successfully created the identity and tries to signin. Before this is investigated to unblock the build disabling the test.
@brentschmaltz
=> Disabling the openIdc test to enable coherence

test/E2ETests/Common/DeploymentUtility.cs, test/E2ETests/OpenIdConnectTests.cs, test/E2ETests/compiler/shared/Mocks/OpenIdConnect/OpenIdConnectNotifications.cs
Bug # https://github.com/aspnet/Security/issues/144 is fixed.
Reenabling the test to run on CI.
=> Reenabling the open idconnect test

test/E2ETests/Common/DeploymentUtility.cs, test/E2ETests/Common/Helpers.cs
Setting an increased retry wait time. Now test will wait for 42 seconds before giving up.
@suhasj
=> Removing a fixed waittime of 25 seconds on mono

src/MusicStore/CopyAspNetLoader.cmd
Current script actually ensure the oldest one gets copied. Changed to the opposite which is the desirable behavior.
=> Ensure the latest AspNet.Loader.dll is retrieved

src/MusicStore/Models/MusicStoreContext.cs
Recent change in EF requires the principal root in chain of foreignkey to have GenerateValueOnAdd enabled.
Due to this GenreId & ArtistId requires GenerateValueOnAdd as true. This is done by conventions automatically.
Since explicit values are being inserted in both the columns using sequence instead of Identity (which is also default by convention)
=> Ef : Enabled Autogeneration for ArtistId & GenreId using sequence

test/E2ETests/Common/DeploymentUtility.cs
The command to execute tests have changed to dnx . test. As a result the path to dnx.exe cannot be retrieved from Environment.CommandLineArgs().
Changing the way to obtain path to dnx.exe.
=> Fixing test helpers

src/MusicStore.Spa/compiler/preprocess/RazorPreCompilation.cs, src/MusicStore/compiler/preprocess/RazorPreCompilation.cs
Verified by running kpm build and observed __ASP_ASSEMBLY.__PreGeneratedViewCollection.ctor() has registered all cshtml
=> Add precompiler to allow kre to precompile views

test/E2ETests/PublishAndRunTests.cs
Looks like --no-source is failing with coreclr
=> Changing --no-source variation to use desktop clr

build.sh
Currently due to this command source is not recognized. This seems to be fixed in a bunch of repos already.
=> Updating build.sh to use /bin/bash instead of /bin/sh

src/MusicStore/Views/Shared/_Layout.cshtml
This commit add missing fallback test attribute to script tag helper.
This fix will remove missing fallback attribute warning from console
for this specific tag helper.
Thanks!
=> Add missing helper tag fallback attr. Closes #520

shared/Mocks/StartupOpenIdConnectTesting.cs, shared/Mocks/StartupSocialTesting.cs, src/MusicStore/StartupNtlmAuthentication.cs, src/MusicStore/StartupOpenIdConnect.cs
Some more calls that I missed in my previous commit. The overload being used in the templates has swapped to a builder pattern (see aspnet/Diagnostics#184). But rather than updating to the new signature, just swapping to the parameterless overload since it enables everything by default (same as UseDeveloperExceptionPage()).
=> :green_heart: Fix more calls to UseDatabaseErrorPage

test/E2ETests/OpenIdConnectTests.cs
The OpenIdConnectTests have been skipped on Windows for months. The tests are not up-to-date. Work item #565 is filed to track the work of updating the test. In the meantime, the tests are disabled to make MusicStore pass on Travis.
/cc @Tratcher @cesarbs @muratg
=> Disable OpenIdConnectTests on Mono temporary

test/MusicStore.Test/project.json
This apparently was fine for source dependencies in dnx but appears to cause problems in dotnet.
=> Include version in project.json

MusicStore.sln, MusicStore.sln.DotSettings, shared/MusicStoreConfig.cs, src/MusicStore/Startup.cs, src/MusicStore/config.json, test/E2ETests/Common/DbUtils.cs, test/E2ETests/Common/XunitLogger.cs, test/E2ETests/Implementation/FacebookLoginScenarios.cs, test/E2ETests/Implementation/GoogleLoginScenarios.cs, test/E2ETests/Implementation/MicrosoftAccountAuthenticationScenarios.cs, test/E2ETests/Implementation/OpenIdConnectLoginScenarios.cs, test/E2ETests/Implementation/TwitterLoginScenarios.cs, test/E2ETests/Implementation/Validator.cs, test/E2ETests/NtlmAuthentationTest.cs, test/E2ETests/OpenIdConnectTests.cs, test/E2ETests/PublishAndRunTests.cs, test/E2ETests/SmokeTests.cs, test/E2ETests/project.json, test/MusicStore.Test/Models/ShoppingCartTest.cs
Should fix failing tests. Currently on CI the agents are all using the same database, across concurrent multiple tests. In order to figure out what was wrong, I had to fix these other things to make it easier to diagnose what was going wrong.
- Fix incorrect deployment environment variables
- Utilize xunit logging utility for cleaner, more traceable output
- Cleanup database creation/deletion
- Fix name in R# settings file
cc @kichalla @pranavkm
=> Clean up E2E tests

test/E2ETests/Properties/AssemblyInfo.cs
@muratg @pranavkm @BrennanConroy 
The test instability appears to be caused by concurrency conflicts.  This PR uses is the same restriction we apply to functional tests in IISIntegration and ServerTests.
=> Prevent functional tests from executing concurrently.

test/E2ETests/OpenIdConnectTests.cs, test/E2ETests/SmokeTests.cs
These tests are caused by https://github.com/dotnet/corefx/issues/7440 and will be fixed in RTM. We will reenable these tests once we have their RTM build in a few weeks.
cc @Eilon @DamianEdwards
=> Skip test failures caused by CoreFX bug

src/MusicStore/Program.cs
This is needed to fix the build. Explanation is in the comments.
Review: @mikeharder @Tratcher 
Approval: @Eilon @DamianEdwards
=> Use UseServer() instead of UseKestrel() to allow override in tests

test/E2ETests/OpenIdConnectTests.cs, test/E2ETests/SmokeTests.cs
#627 Tested locally and they are now fixed. @BrennanConroy
=> Reenable tests after CoreFX fix

shared/Mocks/StartupOpenIdConnectTesting.cs, shared/Mocks/StartupSocialTesting.cs, src/MusicStore/Platform.cs, src/MusicStore/Startup.cs, src/MusicStore/StartupOpenIdConnect.cs, test/E2ETests/OpenIdConnectTests.cs, test/E2ETests/SmokeTests.cs
I found this while debugging failures on non-windows CoreCLR build failure. These tests will still fail due to the content length issue but this needs to be fixed too.
cc @pranavkm
=> Use in memory store for non-windows tests

test/E2ETests/SmokeTestHelper.cs
@Tratcher @kichalla 
Win7-Universe tests fail a lot from what looks like a timeout, raising to 15 looks like it works on the failing machine
=> Increase HttpClient timeout

README.md, app.json
Please note that, while I originally added this, I'm no longer working at Heroku. I propose that the button be removed since the buildpack is no longer maintained and is based on Mono, not .NET core.
=> remove app.json

samples/MusicStore.Standalone/Program.cs
@Eilon all the tests pass with this change
Example of how the output directory looks like:
=> Updated content root of musicstore.standalone to enable debugging in VS

test/MusicStore.Test/MusicStore.Test.csproj
- aspnet/Testing#248
- xUnit no longer supports .NET 4.5.1
=> Bump test projects up to .NET 4.5.2

samples/MusicStore/Views/ShoppingCart/Index.cshtml
This pull request fixes an issue with RemoveFromCart. Currently, the RemoveFromCart method in ShoppingCartController returns a ShoppingCartRemoveViewModel as a JsonResult that has properties which are PascalCase (i.e., Message, CartTotal, CartCount, ItemCount, DeleteId). However, the jQuery ajax call gets the data as camelCase (i.e., message, cartTotal, cartCount, itemCount, deleteId). As a result, removing an item from the cart isn't working correctly. Changing the JSON from PascalCase to camelCase fixes the problem.
=> fix remove from cart ajax done

samples/MusicStore/MusicStore.csproj, test/E2ETests/OpenIdConnectTests.cs
We don't want ForTesting to show up in the publish output unless we are testing with it. Currently it seems like OIDC tests are the only tests that actually needs ForTesting folder.
=> Only publish ForTesting folder when needed

test/MusicStore.E2ETests/NtlmAuthentationTest.cs, test/MusicStore.E2ETests/OpenIdConnectTests.cs, test/MusicStore.E2ETests/PublishAndRunTests.cs, test/MusicStore.E2ETests/SmokeTests.cs, test/MusicStore.E2ETests/SmokeTestsOnNanoServer.cs
The `LoggedTest` helper has been moved to `Microsoft.Extensions.Logging.Testing` repo.
React to aspnet/Hosting#1039
=> remove integration test logging

build/dependencies.props, samples/MusicStore/MusicStore.csproj
We made a breaking change to the Razor Sdk (https://github.com/aspnet/Razor/commit/95835d6c37c108ae0788f49ccc0d17f3ba20586e) that requires using a version of Microsoft.NET.Sdk.Razor newer than the one in the CLI. This resolves the issue and fixes test failures.
=> Use the Razor.Sdk package
